package org.aerogear.plugin.intellij.mobile.ui.servicecatalog;

import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * This class is generated by and can be edited using the Netbeans GUI Builder.
 * To edit this file, open the ServicePanel.form file in the NetBeans GUI Builder.
 * To view the generated source code, choose Source within the Netbeans GUI Builder.
 */
public class ServicePanel extends javax.swing.JPanel {

    /**
     * Creates new form ServicePanel
     */
    public ServicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serviceInfo = new javax.swing.JLabel();
        deploy = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));
        setMaximumSize(new java.awt.Dimension(32767, 70));

        serviceInfo.setText("dssf");

        deploy.setText("Deploy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(serviceInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(deploy, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deploy)
                    .addComponent(serviceInfo))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getDeploy() {
        return deploy;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deploy;
    private javax.swing.JLabel serviceInfo;
    // End of variables declaration//GEN-END:variables

    public JLabel getServiceInfo() {
        return serviceInfo;
    }
}
