package org.aerogear.plugin.intellij.mobile.ui.certconfiguration.pinnedcerts;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.intellij.openapi.components.ServiceManager;
import org.aerogear.plugin.intellij.mobile.services.MobileNotificationsService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 * This class is generated by and can be edited using the Netbeans GUI Builder.
 * To edit this file, open the ServicePanel.form file in the NetBeans GUI Builder.
 * To view the generated source code, choose Source within the Netbeans GUI Builder.
 */
public class PinnedCertPanel extends javax.swing.JPanel {
    MobileNotificationsService notifier;

    /**
     * Creates new form KeycloakConfiguration
     */
    DefaultTableModel model;
    public PinnedCertPanel() {
        initComponents();
        model = (DefaultTableModel) tableCerts.getModel();
        notifier = ServiceManager.getService(MobileNotificationsService.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfHostName = new javax.swing.JTextField();
        tfHostURL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCerts = new javax.swing.JTable();
        buttonDelete = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfBuildType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(700, 400));

        jLabel4.setText("Host URL");

        tableCerts.setBorder(null);
        tableCerts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Build Type", "Host Name", "Host URL"
            }
        ));
        tableCerts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCertsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCerts);

        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Build Type");

        tfBuildType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuildTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("Click to edit or delete a pinned cert");

        jLabel3.setText("Host Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 446, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBuildType, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfHostName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfHostURL, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuildType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfHostURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonEdit)
                    .addComponent(buttonDelete))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableCertsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCertsMouseClicked
        tfBuildType.setText(String.valueOf(model.getValueAt(tableCerts.getSelectedRow(), 0)));
        tfHostName.setText(String.valueOf(model.getValueAt(tableCerts.getSelectedRow(), 1)));
        tfHostURL.setText(String.valueOf(model.getValueAt(tableCerts.getSelectedRow(), 2)));
    }//GEN-LAST:event_tableCertsMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        try{
            model.removeRow(tableCerts.getSelectedRow());
        } catch (Exception e) {
            notifier.notifyError("Error, No Row Selected. " , e.toString());
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        try{
            model.setValueAt(tfBuildType.getText(), tableCerts.getSelectedRow(), 0);
            model.setValueAt(tfHostName.getText(), tableCerts.getSelectedRow(), 1);
            model.setValueAt(tfHostURL.getText(), tableCerts.getSelectedRow(), 2);
        } catch (Exception e) {
            notifier.notifyError("Error, No Row Selected. ", e.toString());
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        try{
            model.insertRow(model.getRowCount(), new Object[]{tfBuildType.getText(), tfHostName.getText(), tfHostURL.getText()});
        }catch (Exception e){
            notifier.notifyError("Error: ", e.toString());
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void tfBuildTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuildTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuildTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCerts;
    private javax.swing.JTextField tfBuildType;
    private javax.swing.JTextField tfHostName;
    private javax.swing.JTextField tfHostURL;
    // End of variables declaration//GEN-END:variables


    public JTextField getBuildType() {
        return tfBuildType;
    }

    public JTextField getHostName() {
        return tfHostName;
    }

    public JTextField getHostURL() {
        return tfHostURL;
    }
}
